version: '3'
services:
  redis:
    image: 'redis:latest'
    restart: always
    networks:
      - main
    ports:
      - 6378:6379
    volumes:
      - ./external/redis:/data
  mysql:
    image: mysql:5.7.32
    container_name: db2
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: ${DELIVERY_NODE_DB_NAME}
      MYSQL_USER: ${DELIVERY_NODE_DB_USER}
      MYSQL_PASSWORD: ${DELIVERY_NODE_DB_PASS}
    ports:
      - 3305:3306
    # Change this to your local path
    volumes:
      - ./external/mysql:/var/lib/mysql/
    networks:
      - main

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8182:80
  
  push-delivery-node:
    build: .
    profiles:
      - prod
    restart: always
    networks:
      - main
    ports:
      - 80:${PORT}
    volumes:
      - ./firebase-adminsdk.json:/app/firebase-adminsdk.json:ro
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      DELIVERY_NODES_NET: ${DELIVERY_NODES_NET}
      DELIVERY_NODE_DB_HOST: db2
      DELIVERY_NODE_DB_PORT: 3306
      DELIVERY_NODE_DB_NAME: ${DELIVERY_NODE_DB_NAME}
      DELIVERY_NODE_DB_USER: ${DELIVERY_NODE_DB_USER}
      DELIVERY_NODE_DB_PASS: ${DELIVERY_NODE_DB_PASS}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      PUSH_NODE_WEBSOCKET_URL: ${PUSH_NODE_WEBSOCKET_URL}
      REDIS_URL: redis://redis:6379
    depends_on:
      - mysql
      - redis

networks:
  main:
    driver: bridge
